### ISSUE TITLE
[RFC]: Removal of all tests which test invalid things

### ISSUE THREAD

**Issue by boesing** [laminas/laminas-container-config-test#23]
## RFC

| Q                   | A      |
| ------------------- | ------ |
| Proposed Version(s) | 1.0.0  |
| BC Break?           | No |

### Goal

This RFC targets the fact, that this component provides tests which do verify that no garbage configuration can be passed to a container. The focus of this component should be on verifying that containers can handle valid configurations rather than checking that in case an invalid configuration is passed, the container behaves the same as `laminas-servicemanager`.

### Background

In `laminas-servicemanager` v4, tests like `DelegatorTestTrait#testNonExistentDelegatorClassResultsInExceptionDuringInstanceRetrieval` fail since due to psalm and native type-hints, most stuff can't happen from a type-perspective. This behavior might vary between multiple container implementations and thus, I don't see the point of testing this behavior here.

### Considerations

Implementing containers won't really see a difference since they either already passed these tests or they got rid of these tests in some way.

### Proposal(s)

Removal or refactoring of all tests which verify that the container will throw an exception based on invalid configuration passed.

[DelegatorTestTrait#testNonExistentDelegatorClassResultsInExceptionDuringInstanceRetrieval](https://github.com/laminas/laminas-container-config-test/blob/0caa176667356084ec199ef060f649255191a409/src/DelegatorTestTrait.php#L331-L342)

```php
$container = $this->createContainer($config);
self::assertFalse($container->has($serviceNameToTest));
$this->expectException(ContainerExceptionInterface::class);
$container->get($serviceNameToTest);
```

etc.

**Comment by weierophinney** [comment]
This makes sense. The various PHP-FIG integration tests that validate an implementation against the spec are testing only behavior that is defined in the spec. This is a similar situation: we want to validate that specific features work as expected: can you map factories, aliases, and abstract factories, and can you configure delegators. Since we don't have an interface specfication that defines what happens for invalid configuration, that becomes an implementation detail of the individual implementations.
